// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyeovjfhyhgrizzcitct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5ZW92amZoeWhncml6emNpdGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTkzODcsImV4cCI6MjA3MzM5NTM4N30.Lz-iBmvD-IGFSA3SAWqJ__8sGyy8aM2SBUC3ZYsE6RI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});